import = ["/home/mohsun/.config/alacritty/themes/everforest_dark.toml"]

[font]
size = 13.0

[font.bold]
family = "JetbrainsMono NF"
style = "Bold"

[font.bold_italic]
family = "JetbrainsMono NF"
style = "Bold Italic"

[font.italic]
family = "JetbrainsMono NF"
style = "Italic"

[font.normal]
family = "JetbrainsMono NF"
style = "Regular"

[window]
opacity = 0.95

[window.dimensions]
columns = 101
lines = 29
